MAINT: Reenable MKL (#455)

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -22,7 +22,6 @@ jobs:
     continue-on-error: true
     strategy:
       matrix:
-        # TODO: MKL currently untested on any platform
         # Currently, VTK is only installed+tested on Ubuntu
         # Someday we could use OpenBLAS for Windows once vcpkg sorts things out
         # (https://github.com/microsoft/vcpkg/issues/25176), but it's unclear
@@ -33,6 +32,19 @@ jobs:
         blas_linking: [dynamic]
         python: [python]
         include:
+        # MKL on each OS (static unless it has to be dynamic)
+        - os: windows-2019
+          blas: mkl-findblas
+          blas_linking: static
+          python: python
+        - os: ubuntu-20.04
+          blas: mkl-findblas
+          blas_linking: dynamic
+          python: python
+        - os: macos-latest
+          blas: mkl-findblas
+          blas_linking: static
+          python: python
         # ubuntu-18.04 build, but Python tests currently fail so use no-python
         - os: ubuntu-18.04
           blas: OpenBLAS
@@ -49,31 +61,35 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
-    - name: Environment setup
+    - name: Environment variables
       run: |
-        if [ ${{matrix.blas_linking}} == 'static' ]; then
-          echo "BLA_STATIC_OPT='-DBLA_STATIC=ON'" >> $GITHUB_ENV
+        if [[ "${{matrix.blas_linking}}" == 'static' ]]; then
+          echo "Enabling static BLAS"
+          echo "BLA_STATIC_OPT=-DBLA_STATIC=ON" >> $GITHUB_ENV
         fi
-        if [ ${{matrix.python}} == 'python' ]; then
-          echo "PYTHON_OPT='-DENABLE_PYTHON=ON'" >> $GITHUB_ENV
+        if [[ "${{matrix.python}}" == 'python' ]]; then
+          echo "Enabling Python"
+          echo "PYTHON_OPT=-DENABLE_PYTHON=ON" >> $GITHUB_ENV
         fi
-        if [ ${{matrix.blas}} == 'MKL' ]; then
-          echo "BLA_IMPL=-DBLA_IMPLEMENTATION=MKL" >> $GITHUB_ENV
-          echo "BLA_PARA=-DMKL_PARALLELISM=sequential" >> $GITHUB_ENV
+        if [[ "${{matrix.blas}}" == 'mkl'* ]]; then
+          echo "Setting BLA_IMPLEMENTATION=${{matrix.blas}}"
+          echo "BLA_IMPL=-DBLA_IMPLEMENTATION=${{matrix.blas}}" >> $GITHUB_ENV
         fi
         # Build docs on Ubuntu, not elsewhere (for speed)
-        if [[ ${{matrix.os}} == 'ubuntu'* ]]; then
+        if [[ "${{matrix.os}}" == 'ubuntu'* ]]; then
           BUILD_DOCS=ON
         else
           BUILD_DOCS=OFF
         fi
         # Use -Werror on Windows and macOS, eventually should use on Linux
         if [[ ${{matrix.os}} != 'ubuntu*' ]]; then
-          ENABLE_WERROR=OFF
+          WERROR_OPT="-DENABLE_WERROR=OFF"
         else
-          ENABLE_WERROR=ON
+          WERROR_OPT="-DENABLE_WERROR=ON"
         fi
-        echo "ENABLE_WERROR=$ENABLE_WERROR" >> $GITHUB_ENV
+        echo "Using WERROR_OPT=$WERROR_OPT"
+        echo "WERROR_OPT=$WERROR_OPT" >> $GITHUB_ENV
+        echo "Using DOC_OPT=$DOC_OPT"
         echo "DOC_OPT=-DBUILD_DOCUMENTATION=$BUILD_DOCS" >> $GITHUB_ENV
 
     - name: Setup ccache
@@ -82,7 +98,7 @@ jobs:
         key: ${{ github.job }}-${{ matrix.os }}
 
     # Always use conda for Python
-    - name: Setup Python
+    - name: Python via conda
       uses: conda-incubator/setup-miniconda@v2
       with:
         activate-environment: "test"
@@ -90,7 +106,7 @@ jobs:
         channels: conda-forge
         channel-priority: strict
 
-    - name: Add Python packages
+    - name: Python packages
       if: startswith(matrix.python, 'python')
       run: |
         pip install --upgrade -q pip
@@ -105,33 +121,36 @@ jobs:
         # Fix Miniconda paths
         echo "PYTHON_INFO_OPT=-DPython3_EXECUTABLE=$(which python)" >> $GITHUB_ENV
 
-    - name: MKL setup - mkl via conda
-      if: startswith(matrix.blas,'MKL')
+    - name: MKL setup - mkl viai conda
+      if: startswith(matrix.blas,'mkl')
       run: |
-        conda install mkl mkl-include
+        # To get a local testing env, you can do for example:
+        # $ conda create -n openmeeg-mkl -c conda-forge --strict-channel-priority mkl-devel swig libmatio hdf5 numpy
+        # $ conda activate openmeeg-mkl
+        #
+        # On Windows, locally this static build almost works:
+        # ./build_tools/cmake_configure.sh -DBLA_IMPLEMENTATION=mkl-findblas -DBLA_STATIC=ON -DCMAKE_PREFIX_PATH="$CONDA_PREFIX/Library" -DCMAKE_CXX_FLAGS="-I$CONDA_PREFIX/Library/include" -DENABLE_PYTHON=ON
+        # cmake --build build --config Release
+        #
+        # On Linux, locally this works:
+        # ./build_tools/cmake_configure.sh -DBLA_IMPLEMENTATION=mkl-findblas -DCMAKE_PREFIX_PATH="$CONDA_PREFIX/lib" -DCMAKE_CXX_FLAGS="-I$CONDA_PREFIX/include" -DENABLE_PYTHON=ON
+        # cmake --build build --config Release
+        # cd build && LD_PRELOAD=$CONDA_PREFIX/lib/libmkl_rt.so ctest -C Release
+        #
+        conda install -c conda-forge -q mkl-devel
+        if [[ "${{matrix.os}}" == 'windows'* ]]; then
+          echo "CMAKE_PREFIX_PATH=$(cygpath -m $CONDA_PREFIX/Library)" >> $GITHUB_ENV
+          echo "CMAKE_CXX_FLAGS=-I$(cygpath -m $CONDA_PREFIX/Library/include) ${CMAKE_CXX_FLAGS}" >> $GITHUB_ENV
+        else
+          echo "CMAKE_PREFIX_PATH=$CONDA_PREFIX/lib" >> $GITHUB_ENV
+          echo "CMAKE_CXX_FLAGS=-I$CONDA_PREFIX/include ${CMAKE_CXX_FLAGS}" >> $GITHUB_ENV
+          if [[ "${{matrix.os}}" == 'ubuntu'* ]]; then
+            echo "LD_PRELOAD=$CONDA_PREFIX/lib/libmkl_rt.so" >> $GITHUB_ENV
+          fi
+        fi
 
-    - name: Windows OpenBLAS setup 1 - set env
-      if: startswith(matrix.blas,'OpenBLAS') && startswith(matrix.os,'windows')
-      run: |
-        VCPKG_INSTALLED_DIR="${PWD}/build/vcpkg_installed"
-        echo "$VCPKG_INSTALLED_DIR"
-        VCPKG_INSTALLED_DIR=$(cygpath -m "$VCPKG_INSTALLED_DIR")
-        echo "$VI"
-        echo "VCPKG_INSTALLED_DIR=$VCPKG_INSTALLED_DIR" >> $GITHUB_ENV
-        VCPKG_DEFAULT_TRIPLET=x64-mingw-dynamic
-        echo "VCPKG_DEFAULT_TRIPLET=$VCPKG_DEFAULT_TRIPLET" >> $GITHUB_ENV
-        echo "VCPKG_DEFAULT_HOST_TRIPLET=$VCPKG_DEFAULT_TRIPLET" >> $GITHUB_ENV
-        VCPKG_INSTALL_OPTIONS="--x-install-root=$VCPKG_INSTALLED_DIR --triplet=$VCPKG_DEFAULT_TRIPLET"
-        echo "VCPKG_INSTALL_OPTIONS=$VCPKG_INSTALL_OPTIONS" >> $GITHUB_ENV
-
-        CMAKE_TOOLCHAIN_FILE=${PWD}/vcpkg/scripts/buildsystems/vcpkg.cmake
-        echo "$CMAKE_TOOLCHAIN_FILE"
-        CMAKE_TOOLCHAIN_FILE=$(cygpath -m "$CMAKE_TOOLCHAIN_FILE")
-        echo "$CMAKE_TOOLCHAIN_FILE"
-        echo "CMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}" >> $GITHUB_ENV
-
-    - name: Windows OpenBLAS setup 2 - cache vcpkg
-      if: startswith(matrix.blas,'OpenBLAS') && startswith(matrix.os,'windows')
+    - name: Windows 1 - cache vcpkg
+      if: startswith(matrix.os,'windows')
       uses: actions/cache@v3
       with:
         path: |
@@ -139,24 +158,17 @@ jobs:
           build/vcpkg_installed
         key: vcpkg-${{ hashFiles('**/vcpkg.json') }}-mingw64-0
 
-    - name: Windows OpenBLAS setup 3 - hdf5 and libmatio via vcpkg
-      if: startswith(matrix.blas,'OpenBLAS') && startsWith(matrix.os,'windows')
+    - name: Windows 2 - hdf5 and libmatio via vcpkg
+      if: startsWith(matrix.os,'windows')
       id: runvcpkg
       run: |
-        set -x
-        if [ ! -d vcpkg ]; then
-          git clone https://github.com/Microsoft/vcpkg.git --depth=1
-          cd vcpkg
-          git fetch origin 2022.05.10:use --depth=1
-          git checkout use
-          ./bootstrap-vcpkg.sh
-          cd ..
-        fi
-        echo "VCPKG_INSTALLED_DIR: $VCPKG_INSTALLED_DIR"
-        echo "CMAKE_TOOLCHAIN_FILE: $CMAKE_TOOLCHAIN_FILE"
-        test -f $(cygpath -u "$CMAKE_TOOLCHAIN_FILE")
+        export VCPKG_DEFAULT_TRIPLET=x64-mingw-dynamic
+        source ./build_tools/setup_windows_compilation.sh
+        # On Windows, we tell cmake to copy all runtime deps to the build dir,
+        # and for tests (and Python) to find them, we need to add it to PATH
+        echo "PATH=$(cygpath -w ${PWD}/build);$PATH" >> $GITHUB_ENV
 
-    - name: Windows OpenBLAS setup 4 - OpenBLAS via MacPython download
+    - name: Windows 3 - OpenBLAS via MacPython download
       if: startsWith(matrix.blas,'OpenBLAS') && startsWith(matrix.os,'windows')
       run: |
         # OpenBLAS direct download (too slow to build using vcpkg)
@@ -169,106 +181,82 @@ jobs:
         test -d "$OPENBLAS_LIB"
         echo "$OPENBLAS_INCLUDE"
         test -d "$OPENBLAS_INCLUDE"
-        cd $OPENBLAS_LIB
+        pushd $OPENBLAS_LIB
         ls -al
-        if [[ "${{ matrix.linking }}" != "static" ]]; then
-          cp ../bin/libopenblas_v0.3.18-gcc_8_1_0.dll .
-          cp libopenblas_v0.3.18-gcc_8_1_0.dll openblas.dll
-          mv libopenblas_v0.3.18-gcc_8_1_0.dll.a openblas.dll.a
-        fi
+        # TODO: This conditional should work but it does not...
+        # if [[ "${{ matrix.blas_linking }}" != "static" ]]; then
+        cp ../bin/libopenblas_v0.3.18-gcc_8_1_0.dll .
+        cp libopenblas_v0.3.18-gcc_8_1_0.dll openblas.dll
+        mv libopenblas_v0.3.18-gcc_8_1_0.dll.a openblas.dll.a
+        # fi
         mv libopenblas_v0.3.18-gcc_8_1_0.a openblas.a
         mv libopenblas_v0.3.18-gcc_8_1_0.def openblas.def
         mv libopenblas_v0.3.18-gcc_8_1_0.exp openblas.exp
         mv libopenblas_v0.3.18-gcc_8_1_0.lib openblas.lib
-        cd ../../../
+        popd
         echo "OPENBLAS_LIB=$OPENBLAS_LIB" >> $GITHUB_ENV
         echo "LIB=$(cygpath -w $OPENBLAS_LIB);${LIB}" >> $GITHUB_ENV
-        #echo "CPATH=$(cygpath -w $OPENBLAS_INCLUDE);${CPATH}" >> $GITHUB_ENV
         echo "CMAKE_CXX_FLAGS=-I$(cygpath -m $OPENBLAS_INCLUDE)" >> $GITHUB_ENV
-        echo "CMAKE_GENERATOR=MinGW Makefiles" >> $GITHUB_ENV
-        echo "STRIP_OPT=-DCMAKE_EXE_LINKER_FLAGS=-s -DCMAKE_SHARED_LINKER_FLAGS=-s -DCMAKE_MODULE_LINKER_FLAGS=-s" >> $GITHUB_ENV
 
-        #echo "CMAKE_GENERATOR=Visual Studio 16 2019" >> $GITHUB_ENV
-        #echo "CMAKE_GENERATOR_PLATFORM=x64" >> $GITHUB_ENV
-        #echo "SDK_OPT=-DCMAKE_SYSTEM_VERSION=8.1" >> $GITHUB_ENV
-        #echo "TOOLSET_OPT=-DCMAKE_GENERATOR_TOOLSET=v141" >> $GITHUB_ENV
-
-        # On Windows, we tell cmake to copy all runtime deps to the build dir,
-        # and for tests (and Python) to find them, we need to add it to PATH
-        echo "PATH=$(cygpath -w ${PWD}/build);$PATH" >> $GITHUB_ENV
-        # This makes debugging easier on failure
-        # echo "BUILD_OPT=-j 1" >> $GITHUB_ENV
-        # Finally, print our settings
-        cat $GITHUB_ENV
-
-    - name: macOS OpenBLAS setup - openblas, hdf5, libmatio via brew
-      if: startswith(matrix.blas,'OpenBLAS') && startswith(matrix.os,'macos')
+    - name: macOS - hdf5, libmatio, and (optionally) OpenBLAS via brew
+      if: startswith(matrix.os,'macos')
       run: |
         brew update > /dev/null
-        brew install hdf5 libmatio boost swig openblas
-        BLAS_DIR=/usr/local/opt/openblas
-        echo "Checking for $BLAS_DIR/include"
-        test -d $BLAS_DIR/include
-        echo "Checking for LAPACK"
-        ls -al $BLAS_DIR/include
-        test -f $BLAS_DIR/include/lapack.h
-        ls -al /usr/local/opt/openblas/lib
-        test -f /usr/local/opt/openblas/lib/libopenblas.dylib
-        echo "LDFLAGS=-L/usr/local/opt/openblas/lib" >> $GITHUB_ENV
-        echo "CPPFLAGS=-I$BLAS_DIR/include" >> $GITHUB_ENV
-        echo "CMAKE_CXX_FLAGS=-I$BLAS_DIR/include" >> $GITHUB_ENV
-
-    - name: Linux OpenBLAS setup - hdf5, libmatio, vtk, doxygen, and (optionally) OpenBLAS via apt
-      if: startsWith(matrix.os,'ubuntu') && startswith(matrix.blas,'OpenBLAS')
-      run: |
-        sudo apt update
-        if [[ "${{ matrix.blas }}" == "OpenBLAS" ]]; then
-          EXTRA_APT=libopenblas-dev
+        if [[ "${{matrix.blas}}" == "OpenBLAS" ]]; then
+          BREW_EXTRA=openblas
         fi
-        sudo apt -yq install liblapacke-dev doxygen graphviz libhdf5-dev libmatio-dev libvtk7-dev lcov $EXTRA_APT
+        brew install hdf5 libmatio boost swig $BREW_EXTRA
+        if [[ "${{matrix.blas}}" == "OpenBLAS" ]]; then
+          BLAS_DIR=/usr/local/opt/openblas
+          echo "Checking for $BLAS_DIR/include"
+          test -d $BLAS_DIR/include
+          echo "Checking for LAPACK"
+          ls -al $BLAS_DIR/include
+          test -f $BLAS_DIR/include/lapack.h
+          ls -al /usr/local/opt/openblas/lib
+          test -f /usr/local/opt/openblas/lib/libopenblas.dylib
+          echo "CMAKE_CXX_FLAGS=-I$BLAS_DIR/include -L$BLAS_DIR/lib" >> $GITHUB_ENV
+          echo "CMAKE_PREFIX_PATH=$BLAS_DIR" >> $GITHUB_ENV
+        fi
+
+    - name: Linux - hdf5, libmatio, vtk, doxygen, and (optionally) OpenBLAS via apt
+      if: startsWith(matrix.os,'ubuntu')
+      run: |
+        sudo apt update -q
+        if [[ "${{ matrix.blas }}" == "OpenBLAS" ]]; then
+          APT_EXTRA=libopenblas-dev
+        fi
+        sudo apt -yq install liblapacke-dev doxygen graphviz libhdf5-dev libmatio-dev libvtk7-dev lcov $APT_EXTRA
 
     - name: Configure
       run: |
-        set -x
-        cmake -B build \
-              -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
-              ${{env.BLA_STATIC_OPT}} \
-              ${{env.BLA_IMPL}} \
-              ${{env.BLA_PARA}} \
-              ${{env.PYTHON_OPT}} \
-              ${{env.DOC_OPT}} \
-              ${{env.SDK_OPT}} \
-              ${{env.TOOLSET_OPT}} \
-              ${{env.PYTHON_INFO_OPT}} \
-              ${{env.STRIP_OPT}} \
-              -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-              -DCMAKE_C_COMPILER_LAUNCHER=ccache \
-              -DCMAKE_TOOLCHAIN_FILE=${{ env.CMAKE_TOOLCHAIN_FILE }} \
-              -DCMAKE_CXX_FLAGS=${{ env.CMAKE_CXX_FLAGS }} \
-              -DENABLE_WERROR=${{ env.ENABLE_WERROR }} \
-              -DTEST_HEAD3=ON
+        source ./build_tools/cmake_configure.sh
 
     - name: Build
       run: |
-        cmake --build build ${{env.BUILD_OPT}} --config ${{env.BUILD_TYPE}}
+        cmake --build build --config ${{env.BUILD_TYPE}}
         ls -al build
         if [ -d build/wrapping/python/openmeeg ]; then
           ls -al build/wrapping/python/openmeeg
+        else
+          echo "No Python wrapping found"
         fi
 
-    - name: Prepare Python
+    - name: Prepare Python for OpenBLAS
       if: startswith(matrix.python, 'python')
       # Let's make it easy for delvewheel to find the stuff it might need
       run: |
-        if [[ ${{matrix.os}} == 'windows'* ]]; then
+        if [[ "${{matrix.os}}" == 'windows'* ]]; then
           cd build
           echo "Before:"
-          ls -al *.dll
-          if [[ "${{ matrix.linking }}" != "static" ]]; then
+          ls -al *.dll || true
+          if [[ "${{matrix.blas}}" == "OpenBLAS" ]]; then
+            #if [[ "${{ matrix.blas_linking }}" != "static" ]]; then
             strip $OPENBLAS_LIB/libopenblas_v0.3.18-gcc_8_1_0.dll
             cp $OPENBLAS_LIB/libopenblas_v0.3.18-gcc_8_1_0.dll .
             cp $OPENBLAS_LIB/libopenblas_v0.3.18-gcc_8_1_0.dll openblas.dll
-          fi
+            #fi
+          fi;
           cp /mingw64/bin/libgcc_s_seh-1.dll .
           cp /mingw64/bin/libwinpthread-1.dll .
           cp /c/Strawberry/c/bin/libquadmath-0.dll .
@@ -278,6 +266,8 @@ jobs:
           cp /mingw64/bin/zlib1.dll .
           cp OpenMEEGMaths/libmatio.dll .
           cp -a *.dll wrapping/python/openmeeg
+          echo "After:"
+          ls -al *.dll || true
           cd ..
         fi
 
@@ -287,15 +277,16 @@ jobs:
         cd build/wrapping/python
         python setup.py bdist_wheel sdist
         echo "Wheels:"
-        ls -al dist/*.whl
+        ls -alR dist/*.whl
         unzip dist/*.whl -d check
         echo "Contents before:"
-        ls -al check/*
+        ls -alR check/*
         if [[ ${{matrix.os}} == 'windows'* ]]; then
           PATH="$(cygpath -w $PWD/openmeeg);$PATH" delvewheel show dist/*.whl
           PATH="$(cygpath -w $PWD/openmeeg);$PATH" delvewheel repair -w dist dist/*.whl
         elif [[ ${{matrix.os}} == 'macos'* ]]; then
-          delocate-wheel dist/*.whl
+          delocate-wheel -v dist/*.whl
+          delocate-listdeps --all dist/*.whl
         # This build uses a toolchain that is too new, so skip this on Linux
         # else
         #   auditwheel show dist/*.whl
@@ -304,7 +295,7 @@ jobs:
         rm -Rf check
         unzip dist/*.whl -d check
         echo "Contents after:"
-        ls -al check/*
+        ls -alR check/*
         twine check dist/*
         pip install dist/*.whl --force-reinstall
         cd ~
